include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: false
    prefer_const_literals_to_create_immutables: false
    lowercase_with_underscores: false
    prefer_const_constructors: false
    camel_case_types: false
    use_key_in_widget_constructors: false
    file_names: false
    curly_braces_in_flow_control_structures: false
    sized_box_for_whitespace: false
    prefer_typing_uninitialized_variables: false
    avoid_print: false
    prefer_final_fields: false
    prefer_const_declarations: false
    deprecated_member_use: false
    non_constant_identifier_names: false
    must_be_immutable: false
    avoid_unnecessary_containers: false
    sort_child_properties_last: false
    depend_on_referenced_packages: false
