name: studento
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.9+8

environment:
  sdk: ">=2.18.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  advance_pdf_viewer: ^2.0.1
  after_layout: ^1.2.0
  another_flushbar: ^1.12.29
  assorted_layout_widgets: ^7.0.0
  beamer: ^0.11.0
  bot_toast: ^4.0.3
  build_runner: ^2.3.2
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^7.0.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_inappwebview: ^5.7.2+3
  flutter_launcher_icons: ^0.11.0
  flutter_markdown: ^0.6.12
  flutter_pdfview: ^1.2.5
  flutter_staggered_grid_view: ^0.4.0
  fullscreen: ^1.0.3
  functional_widget_annotation: ^0.10.0
  google_mobile_ads: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.3
  launch_review: ^3.0.1
  liquid_swipe: ^3.0.0
  numberpicker: ^2.1.1
  open_filex: ^4.3.2
  package_info_plus: ^3.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  purchases_flutter: ^4.3.0
  quiver: ^3.1.0
  resizable_widget: ^1.0.5
  rxdart: ^0.27.7
  scoped_model: ^2.0.0
  seo_renderer: ^0.6.0
  share_extend: ^2.0.0
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  showcaseview: ^2.0.0+1
  sqflite: ^2.1.0+1
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0

dev_dependencies:
  auto_size_text: ^3.0.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  provider: ^6.0.4
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/launcher-icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/json/
    - assets/icons/
    - assets/illustrations/
    - assets/illustrations/no-classes.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Playfair-Display/PlayfairDisplay-Black.ttf
          weight: 900
